services:
  - type: web
    name: et-otp-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.bot
    autoDeployTrigger: commit
    healthCheckPath: /healthz
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: FASTX_API_KEY
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: LOG_LEVEL
        value: INFO
